appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: fe8w5FPgMzIsrsKl5PQ/JHFQLe4l0DuSksQWZ2AqT+BIxYpsPSroHKwPTJhOwXvOPx/UrLaU/giVr89A9YoUpGvHW7x4BVW9MgLlOOGx5adbrNLx9ZH4OwdidLq54ZNfureSZCjzwML0fA1jLB0im6wgZ/fJcfe8ySs3AVL71fzUfh2pGk7gd7DSx1ctk6nLGlkRnTqmj720Ss/CEDkhZN9UKsY3GI7PpNg6OrBCXOyRVRQGdPzgt7/8ae4rAvFNhZ8hFBpVYmv1Im7PfBUtWuDwwsQ/vxtu1zlpSKeadMzZRRQG4WHzyNQhGkx2vnO8uv9i4SyrbQAGgP/jVqsoC36Oj57Dr6mjO76Xv9wW6iSmKXZTsfubgjWFZ3Wb8fqyOT9EAiNtDKvgMvRQk7zQoLU2urpDw6FztgQ1NlhCSbM4INzFFVsTmAHZ5U4aUAPligbcr80jdce2ILD2GZIO8h/wQPgTlcHoZ4qtYMQFsi2zb/XScjPFOlke5k1H1rTQtkEMmGWJG2gg6KlfGsBFapOd8QcwqBOVSakcea59/eiFLn9P0GymsDeOgdx8donvXdap4KK99TBVJykFG3UwyF7yeBRpzF3olH5e49PoepgTncHyhMptqSLJaoON8Zqff45sPSJGw7zY1PWEVKqEu0SzSG7pC0liVXmiRPmQbxI=
conda_forge_output_validation: false
